# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b8edc1d13e5ea2bf0bcaae807cc306b153213aadd626a5c31bda3ebd63a3458d551ca18dffec5488dd3227b7cc6deecbb0050984998746d4f1e15e030ed1bd7

test:
  secret_key_base: 02894194f949f5eeccd4b059539312cab18d9d74fd0215c3c67640633575a8c7410c56d376db006a89caf3fef2f04eb5e95278880cb0d2ffa5390184ceb60988

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
